import { buildTrials } from "./trials.js";

export const INSTRUCTIONS_TEXT = "In this survey, you will evaluate responses generated by AI systems.\n\nYou will be shown a user question followed by two different AI generated answers.\n\nYour task is to carefully read both responses and select the one you prefer.\n\nThere are no trick questions and no correct or incorrect answers. We are interested in your natural preference.\n\nThe survey includes 10 evaluation tasks and a short feedback section at the end. It should take approximately 8 minutes to complete.\n\nPlease read each response attentively before making your selection.";

export function makeInitialSurveyState() {
  const { seed, trials } = buildTrials();

  return {
    participant: {
      prolificId: "",
      age: "",
      gender: "",
      education: "",
      country: "",
      consent: false
    },

    // store the randomized trials in state so they don't change mid-survey
    trials,

    // one choice per trial (not two-stage anymore)
    answers: trials.map((t) => ({
      trialId: t.trialId,
      chosenOptionId: null,        // "AT" | "AF" | "BT"
      shownOrder: t.options.map(o => o.optionId) // e.g. ["AF","AT"]
    })),

    feedback: {
      accuracyImportance: null,
      incorrectInfoOk: null,
      admitDontKnowBest: null,
      trustWhenAdmits: null,
      chatgptExperience: null,
      //falsePreferenceExplain: "",
      comments: ""
    },

    meta: {
      version: "v2",
      startedAt: new Date().toISOString(),
      finishedAt: null,
      randomSeed: seed
    }
  };
}
